### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/dirs-dev/directories-jvm/issues/36.
Fixes https://github.com/dirs-dev/directories-jvm/issues/37.

Manually checked that everything works fine on Windows (10).

### CODE REVIEW

**Comment by alexarchambault** [comment]
`-NoInteractive` shouldn't actually be used… It null-ifies the output.

**Comment by soc** [comment]
Thanks @alexarchambault!

Do you need a backport to the old artifact, too?

**Comment by alexarchambault** [comment]
> Do you need a backport to the old artifact, too?

What do you mean? coursier was already on the latest `main` before the merge.

**Comment by soc** [comment]
No, I meant if you think it would be useful to backport this for people who are stuck on the `io.github.soc` artifact.

**Comment by alexarchambault** [comment]
No idea if there are people still using the `io.github.soc` artifacts. They'll get the fix when they'll switch to the new organization…

**Pull request merged**
